#
# Configure Zabbix template
#

- name: Enable sudoers.d file lookup
  lineinfile: dest=/etc/sudoers regexp="includedir" line="#includedir /etc/sudoers.d"
  tags:
  - zabbix
  - sudo
  - ceph

- name: Copy Zabbix sudoers profile
  copy: src=zabbix_sudoers_file dest=/etc/sudoers.d/zabbix_sudoers_file mode=0440
  tags:
  - zabbix
  - sudo
  - ceph

- name: Configure zabbix template
  template: src=zabbix_agent.conf.j2 dest=/etc/zabbix_agent.conf
  tags:
  - zabbix
  - configuration

- name: Configure zabbix agentD template
  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix_agentd.conf
  tags:
  - zabbix
  - configuration
  - ceph

- name: Copy ceph scripts for zabbix user params
  copy: src=ceph-status.sh dest=/var/lib/zabbix/ceph-status.sh mode=755 owner=zabbix group=root
  tags:
  - zabbix
  - configuration
  - scripts
  - ceph

- name: Create user parameters directory
  shell: mkdir -p /etc/zabbix_agentd.conf.d/
  tags:
  - zabbix
  - configuration
  - ceph

- name: Copy the zabbix User Parameters file
  copy: src=zabbix_agent_ceph_plugin.conf dest=/etc/zabbix_agentd.conf.d/zabbix_agent_ceph_plugin.conf
  tags:
  - zabbix
  - configuration
  - ceph

- name: Configure ACL for ceph config directory
  acl: name=/etc/ceph entity=zabbix etype=user permissions="x" state=present

- name: Configure ACL for ceph config directory
  acl: name={{ item }} entity=zabbix etype=user permissions="r" state=present
  with_items:
  - /etc/ceph/ceph.conf
  - /etc/ceph/ceph.client.admin.keyring
  tags:
  - ceph
  - zabbix
  - configuration

- name: Restart Zabbix Agent
  service: name=zabbix-agent state=restarted
  tags:
  - zabbix
  - service
  - ceph
